[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
  NODE_OPTIONS = "--max_old_space_size=4096"

[build]
  base = "FrontEnd/dist"
  command = "npm run build"
  publish = "FrontEnd/dist"  